defaults: &defaults
  working_directory: ~/report
  docker:
    - image: paperist/alpine-texlive-ja:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Make pdf
          command: ptex2pdf -l report.tex
      - run:
          name: Install packages
          command: |
            apk add --no-cache ca-certificates
      - persist_to_workspace:
          root: ~/report
          paths:
            - report.pdf

  upload:
    <<: *defaults
    steps:
      - run:
          name: Install packages
          command: |
            apk add --no-cache ca-certificates curl
      - attach_workspace:
          at: ~/report
      - store_artifacts:
          path: report.pdf
      - run:
          name: Slack test
          command: |
            curl -XPOST -d "token=${SLACK_TOKEN}" \
                        -d "username=${SLACK_USERNAME}" \
                        -d "icon_emoji=${SLACK_ICON_EMOJI}" \
                        -d "channel=${SLACK_CHANNEL}" \
                        -d "text=最新のPDFだよ https://${CIRCLE_BUILD_NUM}-114240643-gh.circle-artifacts.com/0/root/report/report.pdf" \
                        "https://slack.com/api/chat.postMessage"

workflows:
  version: 2
  do:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only: master
