defaults: &defaults
  working_directory: ~/report
  docker:
    - image: paperist/alpine-texlive-ja:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Make pdf
          command: ptex2pdf -l report.tex
      - run:
          name: Install packages
          command: |
            apk add --no-cache ca-certificates
      - persist_to_workspace:
          root: ~/report
          paths:
            - report.pdf


  upload:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/report
      - run:
          name: Install packages
          command: |
            apk add --no-cache ca-certificates
      - store_artifacts:
          path: report.pdf

workflows:
  version: 2
  do:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only: master
