version: 2
jobs:
  build:
    working_directory: ~/report
    docker:
      - image: paperist/alpine-texlive-ja:latest
    steps:
      - checkout
      - run:
          name: Make pdf
          command: ptex2pdf -l report.tex
      - run:
          name: Install packages
          command: |
            apk add --no-cache ca-certificates
      - store_artifacts:
          path: report.pdf
