defaults: &defaults
  working_directory: ~/report
  docker:
    - image: paperist/alpine-texlive-ja:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Make pdf
          command: ptex2pdf -l report.tex
      - run:
          name: Install packages
          command: |
            apk add --no-cache curl
      - persist_to_workspace:
          root: ~/report
          paths:
            - report.pdf

  lint:
    working_directory: ~/report
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt install pandoc
      - restore_cache:
          keys:
            - medical-final-report-{{ checksum "yarn.lock" }}
            - medical-final-report-
      - run:
          name: Install lib
          command: yarn install
      - save_cache:
          key: medical-final-report-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Convert tex to md
          command: |
            for filepath in `git diff HEAD~1 --name-only`
            do
              [[ ! $filepath =~ sections\/.*\.tex$ ]] && continue
              pandoc -t markdown $filepath | $(npm bin)/textlint --stdin -f compact -o lintlog_${filepath#*/}
              sed -i "1i${filepath}" lintlog_${filepath#*/} && echo "\n" >> lintlog_${filepath#*/}
            done && \
            cat lintlog_* > lintlog && rm -f lintlog_* || echo "No tex file"
      - run:
          name: Danger
          command: yarn danger

  upload:
    <<: *defaults
    steps:
      - run:
          name: Install packages
          command: |
            apk add --no-cache curl
      - attach_workspace:
          at: ~/report
      - store_artifacts:
          path: report.pdf
      - run:
          name: Slack test
          command: |
            curl -XPOST -d "token=${SLACK_TOKEN}" \
                        -d "username=${SLACK_USERNAME}" \
                        -d "icon_emoji=${SLACK_ICON_EMOJI}" \
                        -d "channel=${SLACK_CHANNEL}" \
                        -d "text=最新のPDFだよ https://${CIRCLE_BUILD_NUM}-114240643-gh.circle-artifacts.com/0/root/report/report.pdf" \
                        "https://slack.com/api/chat.postMessage"

workflows:
  version: 2
  do:
    jobs:
      - build
      - lint:
          requires:
            - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only: master
