defaults: &defaults
  working_directory: ~/report
  docker:
    - image: paperist/alpine-texlive-ja:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Make dvi
          command: platex report
      - run:
          name: Install packages
          command: |
            apk add --no-cache curl
      - persist_to_workspace:
          root: ~/report
          paths:
            - ./

  lint:
    working_directory: ~/report
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            curl -fSL https://github.com/haya14busa/reviewdog/releases/download/0.9.8/reviewdog_linux_amd64 -o ./reviewdog && \
            chmod +x ./reviewdog
      - restore_cache:
          keys:
            - medical-final-report-{{ checksum "yarn.lock" }}
            - medical-final-report-
      - run:
          name: Install lib
          command: yarn install
      - save_cache:
          key: medical-final-report-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: |
            test $CI_PULL_REQUEST && \
            for filepath in `git diff origin/master --name-only`
            do
              [[ ! $filepath =~ sections\/.*\.tex$ ]] && continue
              echo $filepath
              $(npm bin)/textlint -f checkstyle $filepath | ./reviewdog -f=checkstyle -name="textlint" -ci="circle-ci"
            done || echo "no lint"

  upload:
    <<: *defaults
    steps:
      - run:
          name: Install packages
          command: |
            apk add --no-cache curl
      - attach_workspace:
          at: ~/report
      - run:
          name: Make pdf
          command: dvipdfmx report
      - store_artifacts:
          path: report.pdf
      - run:
          name: Slack test
          command: |
            curl -XPOST -d "token=${SLACK_TOKEN}" \
                        -d "username=${SLACK_USERNAME}" \
                        -d "icon_emoji=${SLACK_ICON_EMOJI}" \
                        -d "channel=${SLACK_CHANNEL}" \
                        -d "text=最新のPDFだよ https://${CIRCLE_BUILD_NUM}-114240643-gh.circle-artifacts.com/0/root/report/report.pdf" \
                        "https://slack.com/api/chat.postMessage"

workflows:
  version: 2
  do:
    jobs:
      - build
      - lint:
          requires:
            - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only: master
